### ISSUE TITLE
evaluation is slow

### ISSUE THREAD

**Issue by gongbudaizhe** [bertinetto/cfnet#10]
Hi, 

good work as always : )

The speed of CFNet-conv2 reported in the paper is 75 fps. But when I evaluate this model in OTB-2013, it ran less than 3 fps.  I am using NVIDIA GTX 1080, cuda 8.0, cudnn 5.1.  Matconvnet is compiled with GPU.

Is there anything I might be missing?

**Comment by bertinetto** [comment]
I think you might have the visualization on?
That speed has been reported (clearly) without visualization, on a Titan-X and 4GHz machine.

Otherwise maybe there is a problem with your matconvnet.

**Comment by gongbudaizhe** [comment]
The visualization flag is off. Maybe this is not the problem.

Matconvnet is installed following the instructions in the official documentation. No errors during installation.

I evaluated the tracker using the [python version of OTB evaluation toolkit](https://github.com/jwlim/tracker_benchmark) though. It uses Matlab engine to invoke code written in Matlab. Maybe this causes the slow down?

**Comment by bertinetto** [comment]
Yep that might be the case.

**Comment by gongbudaizhe** [comment]
It turns out that Matlab 2016a doesn't support GTX 1080 and recompiles GPU libraries every time a new session is started. More discussions can be found in [this thread](https://cn.mathworks.com/matlabcentral/answers/289457-parallel-gpu-cudakernel-slow-on-gtx-1080)

**Comment by foolwood** [comment]
@gongbudaizhe 
Solution is found here. 
`https://github.com/apache/incubator-mxnet/issues/3239`

export CUDA_CACHE_MAXSIZE=2147483647
export CUDA_CACHE_DISABLE=0

**Comment by gongbudaizhe** [comment]
@foolwood thanks
