### ISSUE TITLE
About the color and gray network and training settings

### ISSUE THREAD

**Issue by YP-Liu** [bertinetto/cfnet#26]
Hi, Luca.
  Thanks for good work.
  To train network for gray and color separately as the networks given, how to set parameters(such as grayscale) for gray and color?
  Thank you very much.

**Comment by bertinetto** [comment]
Hi,
In `experiment.m`, just set `opts.augment.grayscale` to the probability you want.

For the paper, we trained two different networks for rgb (prob=0) and grayscale (prob=1).

But I think it makes more sense to train a single network with something in the range 0.1-0.2
