### ISSUE TITLE
Error occured when I training cfnet on my own dataset

### ISSUE THREAD

**Issue by tigereatsheep** [bertinetto/cfnet#28]
I prepared my training data in the format of VID, and generate the training data as the curation, like this:
imdb_video =

struct with fields:

                 id: [1×168 uint32]
    n_valid_objects: [1×168 uint32]
            nframes: [1×168 uint32]
            objects: {1×168 cell}
               path: {1×168 cell}
total_valid_objects: 83764
  valid_per_trackid: {50×168 cell}
     valid_trackids: [50×168 uint16]
                set: 1
But error occured:
Undefined function or variable 'ideal_size'.

Error in make_branch_alexnet (line 76)
[ideal_exemplar, ~] = ideal_size(net, opts.exemplarSize);

Error in make_net>@()make_branch_alexnet(branch_opts) (line 48)
f = @() make_branch_alexnet(branch_opts);

Error in make_net>make_branches_alexnet (line 49)
branch1 = f();

Error in make_net (line 13)
[branch1, branch2] = make_branches_alexnet(opts);

Error in experiment (line 80)
net = make_net(opts);

Error in run_experiment_baseline_conv5 (line 19)
experiment(imdb_video, opts);

Can you help me ?

**Comment by jvlmdr** [comment]
It did not find `ideal_size.m`. Is `src/util` in the matlab path?

**Comment by tigereatsheep** [comment]
I forgot to set the env. Another error occured. Something wrong in the annotations, I will solve it. Thank you

**Comment by tigereatsheep** [comment]
Hello, I trained on my own dataset, but still some error, Error using datasample (line 158)
Sample size K must be less than or equal to the data size for sampling without replacement.

Error in vid_get_random_batch (line 66)
    rnd_videos = datasample(ids_set, batch_size+num_easy_neg, 'Replace', false);

Error in experiment>get_batch (line 289)
        db, imdb_video, batch, data_dir, sample_opts);

I set all the data as trainingset

**Comment by tigereatsheep** [comment]
solved,
add these

imdb_video.set = ones(1, 332); %%train set
imdb_video.set(332) = 2; %% val set

after load imdb_video
