### ISSUE TITLE
The gaussian response

### ISSUE THREAD

**Issue by huangbiubiu** [bertinetto/cfnet#32]
I found that the Gaussian response in the [gaussian_response.m](https://github.com/bertinetto/cfnet/blob/971e7922b7f0f9140e0d995b598e8d97dece277c/src/util/gaussian_response.m) is not the 2D Gaussian shaped peak centred on the **centre** of the image. I plot the gaussian produced by the code:

![corner](https://user-images.githubusercontent.com/9823705/54827712-9c045300-4ced-11e9-8d79-12a7bbcb1dd8.jpg)

Why the peak is at the corners? Is that on purpose or a bug?

I suppose the gaussian response should look like this:
![center](https://user-images.githubusercontent.com/9823705/54827803-c9510100-4ced-11e9-812e-448cac546b1f.jpg)

I found the difference is at: 
https://github.com/bertinetto/cfnet/blob/971e7922b7f0f9140e0d995b598e8d97dece277c/src/util/circ_grid.m#L1-L7

If change the code to:
```matlab
function [i1, i2] = circ_grid(m1, m2)
    m = [m1, m2];
    [i1, i2] = ndgrid(0:m(1)-1, 0:m(2)-1);
    half = floor((m-1) / 2);
    % i1 = mod(i1 + half(1), m(1)) - half(1);
    % i2 = mod(i2 + half(2), m(2)) - half(2);
    i1 = i1 - half(1);
    i2 = i2 - half(2);
end
```

The peak of gaussian response will the centre of the image.

**Comment by bertinetto** [comment]
Hi,
No it's not a bug, it's intended to be like that :)
See Figure 6 of KCF TPAMI paper.

https://arxiv.org/abs/1404.7584
