### ISSUE TITLE
conv2 filter num of channels is 48

### ISSUE THREAD

**Issue by roipony** [bertinetto/cfnet#6]
Hi,
First of all thank you very much for publishing the code.
In the 2nd conv layer in the pre-trained network "cfnet-conv2_gray_e40.mat" (and also in other pre-trained) the number of channels is 48 (5x5x48x32) while the input(to conv2 layer) num of channels is 96.
I thought the reason is "group" but i cant see the rest of the 5x5x48x32 filter, hence the result of conv2 layer take in account only the first 48 input channels.
Do this deliberately? 
or accidentally, the 2nd group (the rest 5x5x48x32 filters) do not saved in the mat file?

Thank you

**Comment by bertinetto** [comment]
Hi,
We do use filter groups. To understand the behaviour, please have a look at [vl_nnconv documentation of matconvnet](http://www.vlfeat.org/matconvnet/mfiles/vl_nnconv/) .
