### ISSUE TITLE
how to adapt aspect ratio

### ISSUE THREAD

**Issue by raingo** [bertinetto/cfnet#7]
After reading the code, I realized that the aspect ratio is fixed throughout the tracking, because the `make_scale_pyramid` function creates the pyramid evenly along with the width and height.

So the question is: how to adapt to changing aspect ratio?

Thanks!

**Comment by bertinetto** [comment]
Hi,
The code doesn't allow change in aspect-ratio unfortunately.
A simple way to do that is to use a single scale and train a second network which only does bounding box regression.
