### ISSUE TITLE
How can I train baseline+CF-conv3' network?

### ISSUE THREAD

**Issue by yingjieyao** [bertinetto/cfnet#9]
In CFNet's table 1, it shows that the **baseline+CF-conv3** gives the best result. But how can I train this network by myself?
I only show the code in src/training/run_experiment*, which gives the manner to train CFNet-conv1 CFNet-conv2 CFNet-conv5 and baseline-conv5.
Thank you~

**Comment by bertinetto** [comment]
Hi,
Sorry this is probably unclear in the repository.
To get those number we run CFNet-conv3 in feedforward mode, taking the parameters from baseline-conv3.

We share the pretrained network, but if you want to so it yourself you only need to train a baseline conv3 and then have a CFNet of the same size in which insert the weights when you perform tracking.

Here a template for the evaluation:
https://github.com/bertinetto/cfnet/blob/master/src/tracking/run_cfnet3_evaluation.m

Hope it helps!
